url: https://coletiva-ruta.github.io
baseurl: /

# Site settings
title: Coletiva Ruta
email: chaytaniguti@gmail.com
description: "Formada em 2016 por estudantes de Obstetrícia EACH-USP, a Coletiva Ruta promove encontros e conversas sobre autoconhecimento, cuidado e autonomia em saúde."

# Team names, titles and social links
people:
- name: Caroline
  pic: caroline.png
  position: "<p style = 'text-align: justify;'> Carol é catarinense, tem 28 anos (de sonho, sangue e América do Sul) e está no quinto ano de Obstetrícia. Na Coletiva Ruta é da frente de articulação, mídias sociais e responsável pelas finanças. É apaixonada pelo ciclo menstrual. Capricorniana louca das planilhas. Não sabe cochichar. Rouba sotaques. Queria ter na vida simplesmente um lugar de mato verde pra plantar e pra colher, uma casinha branca de varanda, um quintal e uma janela.</p>"

- name: Gabriela
  pic: gabriela.png
  position: "<p style = 'text-align: justify;'> Gabriela tem 27 anos, é paulista, da mais querida zona leste. Atriz, doula e, em breve, obstetriz, que encontra um caminho comum nas artes e nas ciências. Aqui na Ruta cuida da frente de articulação e produção de materiais. É mãe dos xodós Gael e Isa. Filha de Oxum com Oxóssi, tem 'Os Olhos Cheios D'Água'. Caçadora de si mesma, aquariana e diferentona. Ama um samba na palma da mão, num domingo de sol, Corinthians campeão.</p>"

- name: Luísa
  pic: luisa.png
  position: "<p style = 'text-align: justify;'> Luísa tem 22 anos, está a um semestre de se formar obstetriz e é a típica santista que vai à praia uma vez por ano. Na Coletiva Ruta cuida da comunicação, das mídias sociais e do almoxarifado. É loucamente apaixonada por aniversário e detesta astrologia. Não sabe nadar. Adora acessórios esportistas mesmo sem ser uma. Amante da cidade grande que de vez em quando se aventura no meio do mato. Reveza a graduação integral com maracatu, pilates, cerâmica e aprender uma nova língua.</p>"

- name: Rafaela
  pic: rafaela.png
  position: "<p style = 'text-align: justify;'> Rafaela tem 24 anos, pra gente é a Roma e pode ser pra você também. Paulistana, não gosta de São Paulo mas talvez não saiba viver longe dessa doideira. Aqui na Ruta, cuida da identidade visual e dos nossos grupos de estudo. Uma geminiana liberal nas séries (assiste qualquer coisa) e conservadora na pipoca (sal e manteiga, e só). Entusiasta da higiene do sono e do café da manhã. Está no quinto ano de Obstetrícia, costura e toca xequerê, só divide o amor pelo carnaval com a festa junina.</p>"

- name: Veri
  pic: veri.png
  position: "<p style = 'text-align: justify;'> Veri tem 27 anos, é do interior de São Paulo e está no quinto ano de Obstetrícia. Adora tomar café da manhã com calma e come mingau de aveia - por quem nutre uma paixão inexplicável - quase todos os dias. Na coletiva está nas frentes de almoxarifado, grupo de estudos e mídias sociais. Sonha em ser fluente em libras e espanhol, conhecer vários países da América Latina e comer vários tipos de milhos. Tem um Q de queer e ama fazer drag nas horas vagas.</p>"

- name: Ana Clara
  pic: ana_clara.png
  position: "<p style = 'text-align: justify;'> Ana tem 25 anos e é a primeira parteira/obstetriz formada da Coletiva! Paulistana, se joga de cabeça em tudo quanto é oportunidade e tem a capacidade de encostar e dormir em qualquer canto. Aqui na Ruta cuida dos nossos grupos de estudos. Lésbica que se nutre muito estando entre as suas. Entusiasta da abolição do uso rotineiro de calcinhas e sutiãs e da feminilidade. Pseudo-skatista-DJ. Ama estar nas águas (rios e mares), ouvir rap de mulheres latinoamericanas e um sol pra esquentar o corpo.</p>"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/coletivaruta
  - title: instagram
    url: https://www.instagram.com/coletivaruta/
  - title: envelope
    url: coletivaruta@gmail.com
  - title: github
    url: https://github.com/Coletiva-RUTA

# Postal address (add as many lines as necessary)
address:

# Build settings
markdown: kramdown
permalink: pretty